# Generated by Django 5.2.4 on 2025-07-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('clothes', 'Clothes'), ('Dishes', 'Dishes')], default='tech', verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
